Add mocking
polyflix/frontend pull request #45
Opened 2022-12-12 19:41 UTC by thomasgouveia

Closes # 

## 📑 Description

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code is documented
- [ ] I provided unitary tests or procedure to test my code
- [ ] My PR have a clear description of what my code is supposed to do

## ℹ Additional Information

2022-12-12 19:49 UTC, thomasgouveia commented
We will need to update the package manager to use **pnpm** instead of **npm** now.

2022-12-13 12:59 UTC, MaloPolese requested changes

2022-12-13 12:59 UTC, MaloPolese commented on packages/mock-server/fixtures/video.ts
> +    // });
etrange

2022-12-13 13:13 UTC, MaloPolese approved these changes

2022-12-13 13:33 UTC, LeoFVO approved these changes

2022-12-13 13:33 UTC, LeoFVO commented on apps/polyflix/src/environments/docker.environment.ts
> +}
`local.environment.ts` should be more appropriate.

2022-12-13 13:40 UTC, MaloPolese approved these changes

2022-12-13 13:41 UTC, merged